import React, { useEffect, useMemo, useState } from "react";
import { Activity, HeartPulse, RefreshCw, Save, Syringe, Stethoscope, CheckCircle2 } from "lucide-react";
import { api } from "../../services/apiClient";
import { clearSession, getCurrentUser } from "../../services/session";
import { useNavigate } from "react-router-dom";

export default function MedicalDashboard() {
  const navigate = useNavigate();
  const user = getCurrentUser();
  const [animals,setAnimals]=useState([]); const [records,setRecords]=useState([]); const [selected,setSelected]=useState(null); const [loading,setLoading]=useState(true); const [saving,setSaving]=useState(false); const [error,setError]=useState("");
  const [form,setForm]=useState({diagnosis:"",treatmentNotes:"",vaccinationDetails:"",vaccinated:false,sterilized:false,healthStatus:"RECOVERING"});
  async function load(){ setLoading(true); setError(""); try{ const [a,m]=await Promise.all([api.get("/animals"),api.get("/medical")]); setAnimals(Array.isArray(a)?a:[]); setRecords(Array.isArray(m)?m:[]);}catch(e){setError(e.message||"Unable to load medical records.")}finally{setLoading(false);} }
  useEffect(()=>{load();},[]);
  const active=useMemo(()=>animals.filter(a=>["RESCUED","UNDER_TREATMENT","SHELTERED"].includes(String(a.status).toUpperCase())),[animals]);
  const ready=useMemo(()=>animals.filter(a=>a.status==="ADOPTION_READY"),[animals]);
  const vaccinated=useMemo(()=>records.filter(r=>r.vaccinated).length,[records]);
  const selectAnimal=a=>{setSelected(a);setForm({diagnosis:"",treatmentNotes:"",vaccinationDetails:"",vaccinated:false,sterilized:false,healthStatus:"RECOVERING"});};
  async function save(){ if(!selected)return; setSaving(true);setError("");try{await api.post("/medical",{animalId:selected.id,...form}); await load(); setSelected(null);}catch(e){setError(e.message||"Unable to save medical record.")}finally{setSaving(false);} }
  async function markReady(id){setError("");try{await api.patch(`/medical/animal/${id}/ready`);await load();}catch(e){setError(e.message||"Unable to mark adoption-ready.")}}
  function logout(){clearSession();navigate("/login",{replace:true});}
  return <main className="min-h-screen bg-[var(--v-ivory)] px-5 py-10 md:px-8"><div className="mx-auto max-w-7xl">
    <div className="flex flex-col gap-5 md:flex-row md:items-end md:justify-between"><div><p className="text-xs uppercase tracking-[0.18em] font-bold text-[var(--v-terracotta)]">Veterinary care</p><h1 className="v-heading text-4xl md:text-5xl mt-2">Medical care centre.</h1><p className="v-body mt-3 max-w-2xl">Treat the rescued animal, record the clinical journey, and hand healthy animals into the adoption pipeline.</p></div><div className="flex gap-2"><button onClick={load} className="inline-flex items-center gap-2 rounded-xl border border-black/10 bg-white px-4 py-3 font-semibold text-[var(--v-plum)]"><RefreshCw size={16}/> Refresh</button><button onClick={logout} className="rounded-xl bg-[var(--v-forest)] px-4 py-3 font-semibold text-white">Logout</button></div></div>
    {error&&<div className="mt-6 rounded-2xl border border-red-200 bg-red-50 px-5 py-4 text-sm text-red-700">{error}</div>}
    <div className="mt-9 grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><Metric icon={<HeartPulse/>} value={active.length} label="Active care"/><Metric icon={<Activity/>} value={records.length} label="Medical records"/><Metric icon={<Syringe/>} value={vaccinated} label="Vaccinated records"/><Metric icon={<CheckCircle2/>} value={ready.length} label="Adoption ready"/></div>
    <section className="mt-9 grid gap-7 lg:grid-cols-[1.1fr_.9fr]">
      <div className="rounded-3xl bg-white p-6 shadow-[var(--shadow-soft)]"><div className="flex items-center justify-between"><div><p className="text-xs uppercase tracking-widest text-[var(--v-muted)]">Patient queue</p><h2 className="text-2xl font-bold text-[var(--v-plum)] mt-1">Animals needing care</h2></div><Stethoscope className="text-[var(--v-terracotta)]"/></div>
        {loading?<p className="mt-6 text-sm text-[var(--v-muted)]">Loading patients...</p>:active.length===0?<Empty text="No active veterinary cases right now."/>:<div className="mt-6 space-y-3">{active.map(a=><button key={a.id} onClick={()=>selectAnimal(a)} className={`w-full text-left rounded-2xl border p-4 transition ${selected?.id===a.id?"border-[var(--v-terracotta)] bg-[var(--v-terracotta)]/5":"border-black/5 hover:border-[var(--v-terracotta)]/40"}`}><div className="flex items-center justify-between gap-4"><div><div className="font-bold text-[var(--v-plum)]">{a.name||a.microchipId}</div><div className="text-xs text-[var(--v-muted)] mt-1">#{a.id} · {a.species||"Animal"} · {a.status?.replaceAll("_"," ")}</div></div><span className="rounded-full bg-[var(--v-plum)]/8 px-3 py-1 text-[10px] font-bold uppercase tracking-wider text-[var(--v-plum)]">Treat</span></div></button>)}</div>}
      </div>
      <div className="rounded-3xl bg-[var(--v-forest)] p-6 text-white"><p className="text-xs uppercase tracking-widest text-white/55">Clinical handoff</p><h2 className="mt-1 text-2xl font-bold">Selected patient</h2>{!selected?<p className="mt-6 text-sm text-white/65">Select an animal from the queue to record a visit.</p>:<div className="mt-6 space-y-4"><div className="rounded-2xl bg-white/8 p-4"><div className="text-lg font-bold">{selected.name||selected.microchipId}</div><div className="text-xs text-white/60 mt-1">{selected.species} · {selected.breed||"Breed not recorded"}</div></div><input value={form.diagnosis} onChange={e=>setForm({...form,diagnosis:e.target.value})} placeholder="Diagnosis" className="w-full rounded-xl border border-white/10 bg-white/10 px-4 py-3 text-sm outline-none placeholder:text-white/40"/><textarea value={form.treatmentNotes} onChange={e=>setForm({...form,treatmentNotes:e.target.value})} placeholder="Treatment notes" rows="3" className="w-full rounded-xl border border-white/10 bg-white/10 px-4 py-3 text-sm outline-none placeholder:text-white/40"/><textarea value={form.vaccinationDetails} onChange={e=>setForm({...form,vaccinationDetails:e.target.value})} placeholder="Vaccination details" rows="2" className="w-full rounded-xl border border-white/10 bg-white/10 px-4 py-3 text-sm outline-none placeholder:text-white/40"/><select value={form.healthStatus} onChange={e=>setForm({...form,healthStatus:e.target.value})} className="w-full rounded-xl bg-white px-4 py-3 text-sm text-[var(--v-plum)]"><option>RECOVERING</option><option>STABLE</option><option>HEALTHY</option><option>CRITICAL</option><option>READY_FOR_ADOPTION</option></select><div className="grid grid-cols-2 gap-3"><label className="rounded-xl bg-white/8 p-3 text-sm"><input type="checkbox" checked={form.vaccinated} onChange={e=>setForm({...form,vaccinated:e.target.checked})} className="mr-2"/>Vaccinated</label><label className="rounded-xl bg-white/8 p-3 text-sm"><input type="checkbox" checked={form.sterilized} onChange={e=>setForm({...form,sterilized:e.target.checked})} className="mr-2"/>Sterilized</label></div><button onClick={save} disabled={saving} className="w-full rounded-xl bg-[var(--v-terracotta)] px-4 py-3 font-bold disabled:opacity-50"><Save size={16} className="inline mr-2"/>{saving?"Saving...":"Save medical visit"}</button></div>}</div>
    </section>
    <section className="mt-7 rounded-3xl bg-white p-6"><div className="flex items-center justify-between"><div><p className="text-xs uppercase tracking-widest text-[var(--v-muted)]">Lifecycle handoff</p><h2 className="text-2xl font-bold text-[var(--v-plum)] mt-1">Ready for adoption</h2></div></div>{ready.length===0?<Empty text="No animals are marked adoption-ready yet."/>:<div className="mt-5 grid md:grid-cols-2 xl:grid-cols-3 gap-4">{ready.map(a=><div key={a.id} className="rounded-2xl border border-black/5 p-4"><div className="font-bold text-[var(--v-plum)]">{a.name||a.microchipId}</div><div className="text-xs text-[var(--v-muted)] mt-1">{a.species} · {a.breed||"Breed not recorded"}</div><button onClick={()=>markReady(a.id)} className="mt-4 text-xs font-bold text-[var(--v-terracotta)]">Keep adoption-ready</button></div>)}</div>}</section>
  </div></main>
}
function Metric({icon,value,label}){return <div className="rounded-2xl bg-white p-5 shadow-[var(--shadow-soft)]"><div className="text-[var(--v-terracotta)]">{icon}</div><div className="mt-5 text-3xl font-bold text-[var(--v-plum)]">{value}</div><div className="mt-1 text-sm text-[var(--v-muted)]">{label}</div></div>}
function Empty({text}){return <div className="mt-6 rounded-2xl bg-[var(--v-ivory)] p-5 text-sm text-[var(--v-muted)]">{text}</div>}
