import React,{useEffect,useMemo,useState} from "react";
import {Building2,CheckCircle2,Clock3,Heart,LogOut,PawPrint,RefreshCw,XCircle} from "lucide-react";
import {Link,useNavigate} from "react-router-dom";
import {api} from "../../services/apiClient";
import {clearSession,getCurrentUser} from "../../services/session";
export default function ShelterManagementDashboard(){const nav=useNavigate();const user=getCurrentUser();const [animals,setAnimals]=useState([]),[shelters,setShelters]=useState([]),[apps,setApps]=useState([]),[loading,setLoading]=useState(true),[error,setError]=useState(""),[busy,setBusy]=useState(null);
async function load(){setLoading(true);setError("");try{const[a,s,p]=await Promise.all([api.get("/animals"),api.get("/shelters"),api.get("/adoptions")]);setAnimals(Array.isArray(a)?a:[]);setShelters(Array.isArray(s)?s:[]);setApps(Array.isArray(p)?p:[])}catch(e){setError(e.message||"Unable to load shelter operations.")}finally{setLoading(false)}}useEffect(()=>{load()},[]);
const ready=useMemo(()=>animals.filter(a=>a.status==="ADOPTION_READY"),[animals]);const medical=useMemo(()=>animals.filter(a=>a.status==="UNDER_TREATMENT"),[animals]);const pending=useMemo(()=>apps.filter(a=>a.status==="PENDING"),[apps]);
async function updateApp(id,status){setBusy(id);setError("");try{await api.patch(`/adoptions/${id}/status?status=${status}`);await load()}catch(e){setError(e.message||"Unable to update application.")}finally{setBusy(null)}}
async function assign(id,shelterId){setBusy(`s-${id}`);setError("");try{await api.patch(`/animals/${id}/shelter?shelterId=${shelterId}`);await load()}catch(e){setError(e.message||"Unable to assign shelter.")}finally{setBusy(null)}}
function logout(){clearSession();nav("/login",{replace:true})}
return <main className="min-h-screen bg-[var(--v-ivory)] px-5 py-10 md:px-8"><div className="mx-auto max-w-7xl"><div className="flex flex-col gap-5 md:flex-row md:items-end md:justify-between"><div><p className="text-xs uppercase tracking-[0.18em] font-bold text-[var(--v-terracotta)]">Shelter operations</p><h1 className="v-heading text-4xl md:text-5xl mt-2">Care continues here.</h1><p className="v-body mt-3 max-w-2xl">Track capacity, receive rescued animals, and review responsible adoption applications.</p></div><div className="flex gap-2"><button onClick={load} className="inline-flex items-center gap-2 rounded-xl border border-black/10 bg-white px-4 py-3 font-semibold text-[var(--v-plum)]"><RefreshCw size={16}/> Refresh</button><Link to="/shelter/create-animal" className="rounded-xl bg-[var(--v-terracotta)] px-4 py-3 font-bold text-white">Add animal</Link><button onClick={logout} className="rounded-xl bg-[var(--v-forest)] p-3 text-white"><LogOut size={17}/></button></div></div>
{error&&<div className="mt-6 rounded-2xl border border-red-200 bg-red-50 px-5 py-4 text-sm text-red-700">{error}</div>}
<div className="mt-9 grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><Metric icon={<PawPrint/>} value={animals.length} label="Animals in network"/><Metric icon={<Heart/>} value={medical.length} label="Under treatment"/><Metric icon={<CheckCircle2/>} value={ready.length} label="Adoption ready"/><Metric icon={<Clock3/>} value={pending.length} label="Pending applications"/></div>
<section className="mt-9 rounded-3xl bg-white p-6"><div className="flex items-center gap-3"><Building2 className="text-[var(--v-terracotta)]"/><div><p className="text-xs uppercase tracking-widest text-[var(--v-muted)]">Capacity</p><h2 className="text-2xl font-bold text-[var(--v-plum)]">Shelter network</h2></div></div>{loading?<p className="mt-6 text-sm text-[var(--v-muted)]">Loading...</p>:<div className="mt-6 grid gap-4 md:grid-cols-2 xl:grid-cols-3">{shelters.map(s=><div key={s.id} className="rounded-2xl border border-black/5 p-5"><div className="flex justify-between gap-4"><div><div className="font-bold text-[var(--v-plum)]">{s.name}</div><div className="text-xs text-[var(--v-muted)] mt-1">{s.location}</div></div><div className="text-right"><div className="text-lg font-bold text-[var(--v-plum)]">{s.currentOccupancy}/{s.totalCapacity}</div><div className="text-[10px] uppercase tracking-wider text-[var(--v-muted)]">occupied</div></div></div><div className="mt-4 h-2 rounded-full bg-[var(--v-ivory)] overflow-hidden"><div className="h-full rounded-full bg-[var(--v-terracotta)]" style={{width:`${Math.min(100,Math.round((s.currentOccupancy/Math.max(1,s.totalCapacity))*100))}%`}}/></div><div className="mt-2 text-xs text-[var(--v-muted)]">{s.availableSpace} spaces available</div></div>)}</div>}</section>
<section className="mt-7 grid gap-7 lg:grid-cols-[1fr_1fr]"><div className="rounded-3xl bg-white p-6"><p className="text-xs uppercase tracking-widest text-[var(--v-muted)]">Animal intake</p><h2 className="text-2xl font-bold text-[var(--v-plum)] mt-1">Assign rescued animals</h2><div className="mt-5 space-y-3">{animals.filter(a=>!a.shelterId&&a.status!=="ADOPTED").map(a=><div key={a.id} className="rounded-2xl border border-black/5 p-4"><div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div><div className="font-bold text-[var(--v-plum)]">{a.name||a.microchipId}</div><div className="text-xs text-[var(--v-muted)] mt-1">{a.species} · {a.status?.replaceAll("_"," ")}</div></div><select defaultValue="" onChange={e=>e.target.value&&assign(a.id,e.target.value)} disabled={busy===`s-${a.id}`} className="rounded-xl border border-black/10 bg-white px-3 py-2 text-sm"><option value="">Choose shelter</option>{shelters.filter(s=>s.availableSpace>0).map(s=><option key={s.id} value={s.id}>{s.name} ({s.availableSpace} free)</option>)}</select></div></div>)}{animals.filter(a=>!a.shelterId&&a.status!=="ADOPTED").length===0&&<Empty text="All active animals are assigned to a shelter."/>}</div></div>
<div className="rounded-3xl bg-[var(--v-forest)] p-6 text-white"><p className="text-xs uppercase tracking-widest text-white/55">Adoption desk</p><h2 className="text-2xl font-bold mt-1">Review applications</h2><div className="mt-5 space-y-3">{pending.map(app=><div key={app.id} className="rounded-2xl bg-white/8 border border-white/10 p-4"><div className="flex justify-between gap-3"><div><div className="font-bold">Animal #{app.animalId}</div><div className="text-xs text-white/55 mt-1">{app.adopterEmail}</div></div><span className="text-xs text-white/55">#{app.id}</span></div><div className="mt-4 flex gap-2"><button disabled={busy===app.id} onClick={()=>updateApp(app.id,"APPROVED")} className="flex-1 rounded-xl bg-white text-[var(--v-forest)] px-3 py-2 text-sm font-bold"><CheckCircle2 size={15} className="inline mr-1"/> Approve</button><button disabled={busy===app.id} onClick={()=>updateApp(app.id,"REJECTED")} className="rounded-xl border border-white/15 px-4 py-2 text-sm font-bold text-white"><XCircle size={15} className="inline mr-1"/> Reject</button></div></div>)}{pending.length===0&&<p className="text-sm text-white/60">No pending applications.</p>}</div></div></section>
<section className="mt-7 rounded-3xl bg-white p-6"><p className="text-xs uppercase tracking-widest text-[var(--v-muted)]">Approved handoffs</p><h2 className="text-2xl font-bold text-[var(--v-plum)] mt-1">Complete adoptions</h2><div className="mt-5 grid md:grid-cols-2 gap-4">{apps.filter(a=>a.status==="APPROVED").map(a=><div key={a.id} className="rounded-2xl border border-black/5 p-4 flex items-center justify-between gap-4"><div><div className="font-bold text-[var(--v-plum)]">Animal #{a.animalId}</div><div className="text-xs text-[var(--v-muted)] mt-1">Approved for {a.adopterEmail}</div></div><button disabled={busy===a.id} onClick={()=>updateApp(a.id,"COMPLETED")} className="rounded-xl bg-[var(--v-terracotta)] px-4 py-2 text-sm font-bold text-white">Complete adoption</button></div>)}{apps.filter(a=>a.status==="APPROVED").length===0&&<Empty text="Approved applications will appear here."/>}</div></section>
</div></main>}
function Metric({icon,value,label}){return <div className="rounded-2xl bg-white p-5 shadow-[var(--shadow-soft)]"><div className="text-[var(--v-terracotta)]">{icon}</div><div className="mt-5 text-3xl font-bold text-[var(--v-plum)]">{value}</div><div className="mt-1 text-sm text-[var(--v-muted)]">{label}</div></div>}function Empty({text}){return <div className="rounded-2xl bg-[var(--v-ivory)] p-4 text-sm text-[var(--v-muted)]">{text}</div>}
